name: hexo-server
services:
    hexo:
        container_name: hexo
        environment:
            - HEXO_SERVER_PORT=80
        volumes:
            # - ./:/app
            - ./source:/app/source
            - ./scaffolds:/app/scaffolds
            - ./themes:/app/themes
            - ./_config.yml:/app/_config.yaml
            - ./package.json:/app/package.json
            - ./package-lock.json:/app/package-lock.json
            - ./README.md:/app/README.md
        ports:
            - 4000:80
        build: .