name: Deploy Blog Page
on: push

jobs:
  deploy:
    name: deploy job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: install_hexo
      run: npm -g install hexo-cli@^3.1.0
    - name: install_deployer
      run: npm install |
           npm install hexo-deployer-git@^2.1.0 --save
    - name: generate
      run: hexo clean |
           hexo generate
    - name: deploy
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: hexo deploy
