name: Deploy Blog Page
on: push

jobs:
  deploy:
    name: deploy job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: install_hexo
      run: npm -g install hexo-cli@^4.2.0
    - name: install_deployer
      run: npm install
    - name: generate
      run: hexo clean |
           hexo generate
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public